// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.jb.domain;

import com.sut.jb.domain.Kll;

privileged aspect Kll_Roo_JavaBean {
    
    public String Kll.getNui() {
        return this.nui;
    }
    
    public void Kll.setNui(String nui) {
        this.nui = nui;
    }
    
}
