// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.jb.domain;

import com.sut.jb.domain.Kll;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Kll_Roo_Configurable {
    
    declare @type: Kll: @Configurable;
    
}
